### ISSUE TITLE
For Modbus/TCP, throws "ERR_SOCKET_CLOSED" exception on first read, then works.

### ISSUE THREAD

**Issue by ryangriggs** [tbarnhill/modbus#1]
On the first attempt to readafter defining the connection, the code throws an exception because it's apparently not yet connected.  On subsequent requests, it works.   It appears the first attempt establishes a connection.  But this should already be established so we don't get the exception thrown.

Example, taken directly from the website:
```
const modbus = require('modbus')
const device = modbus('192.168.1.90',502,1) 
device.read('c0').then(x=>console.log(x))
```

Throws this exception on first try. Then on next try, it works.
> Uncaught:
<ref *1> Error [ERR_SOCKET_CLOSED]: Socket is closed
    at Socket._writeGeneric (net.js:775:8)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at Object.Tcp.rtn.send (/home/zfi/node_modules/modbus/script.js:293:20)
    at Object.Modbus.rtn.read (/home/zfi/node_modules/modbus/script.js:49:20)
    at REPL15:1:8
    at Script.runInThisContext (vm.js:132:18)
    at REPLServer.defaultEval (repl.js:484:29)
    at bound (domain.js:430:14) {
  code: 'ERR_SOCKET_CLOSED',
  domainEmitter: Socket {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: true,
      emitClose: false,
      autoDestroy: false,
      destroyed: false,
      errored: [Circular *1],
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Function: onReadableStreamEnd],
      data: [Function (anonymous)],
      close: [Function (anonymous)],
      connect: [Array]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: true,
      emitClose: false,
      autoDestroy: false,
      errored: [Circular *1],
      closed: false,
      closeEmitted: false
    },
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: null,
    _server: null,
    [Symbol(async_id_symbol)]: -1,
    [Symbol(kHandle)]: null,
    [Symbol(kSetNoDelay)]: false,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesRead)]: 0,
    [Symbol(kBytesWritten)]: 0
  },
  domainThrown: false
}

**Comment by tbarnhill** [comment]
Thanks for pointing this out. I'll fix this ASAP

**Comment by tbarnhill** [comment]
I am unable to recreate the issue. Can you give more information about your set up? 

I believe the issue must be on line 291 in the script.js file. If there is no connection it is supposed to create one before sending any information
  ```
  rtn.send=(data)=>{
        if(client.writable){
            client.write(data)
        }
        else{
            connect(()=>{client.write(data)})
        }
    }
```

**Comment by tbarnhill** [comment]
Closed because the issue could not be replicated

**Comment by ryangriggs** [comment]
Hi Tyler, I'm requesting to reopen this bug because I've tested on both Windows 10 (64 bit) and Raspberry Pi (Raspbian 10) against two different Modbus/TCP slave devices which have worked fine with other Modbus libraries.  Please let me know if I'm missing something obvious.  Are you able to execute my code below with no errors?


Here's the code:
```
const DEBUG = true;
l('Starting up...');
try
{
	l("Requiring...");
	const modbus = require('modbus');
	l("Defining connection...");
	const device = modbus('192.168.1.91', 502, 1);
	l("Starting...");
	start(device);
}
catch(e)
{
	l("Caught error:", e);
}


function l(){
	if (DEBUG){
		console.log(process.hrtime(), ...arguments);
	}
}


function start(device)
{
	l("Reading c0...");
	device.read('c0')	// Read coil 0
	.then((v) => {
		l("C0: ", v);
	})
	.catch((err) => {
		l("Read error: ", err);
	});

	// l("Reading c0 again...");
	// device.read('c0')	// Read coil 0
	// .then((v) => {
	// 	l("C0: ", v);
	// })
	// .catch((err) => {
	// 	l("Read error: ", err);
	// });
}
```


Here's the output:

```
 node conn-test.js
[ 1643393, 801877257 ] Starting up...
[ 1643393, 850612853 ] Requiring...
[ 1643393, 858405800 ] Defining connection...
[ 1643393, 862907142 ] Starting...
[ 1643393, 864059326 ] Reading c0...
tx: 0002000000060101ffff0001
[ 1643393, 937653447 ] Reading c0 again...
tx: 0003000000060101ffff0001
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_SOCKET_CLOSED]: Socket is closed
    at Socket._writeGeneric (net.js:775:8)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at Object.Tcp.rtn.send (/home/pi/vision/mb2/node_modules/modbus/script.js:293:20)
    at Object.Modbus.rtn.read (/home/pi/vision/mb2/node_modules/modbus/script.js:49:20)
    at start (/home/pi/vision/mb2/conn-test.js:28:9)
    at Object.<anonymous> (/home/pi/vision/mb2/conn-test.js:10:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at errorOrDestroy (internal/streams/destroy.js:168:7)
    at onwriteError (_stream_writable.js:391:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_SOCKET_CLOSED'
}
```

**Comment by tbarnhill** [comment]
Issue reopened

**Comment by tbarnhill** [comment]
I let this drop over the holidays. I am looking into it today.

**Comment by tbarnhill** [comment]
Does this work on your system?
```
async function start(device){
	l("Reading c0...")
	let v = await device.read('c0')	// Read coil 0
	l("C0: ", v)

        l("Reading c0 again...")
        v = await device.read('c0')	// Read coil 0
        l("C0: ", v)

}
```

**Comment by dev-guccin** [comment]
I had the same problem. The problem occurs in node 14.16 version, but the problem does not occur in 8.17. 

```
tx: 000200000006010300000002
tx: 0003000000060106000000c8
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_SOCKET_CLOSED]: Socket is closed
    at Socket._writeGeneric (net.js:775:8)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Object.Tcp.rtn.send (C:\Users\KJH\Desktop\통신\node_modules\modbus\script.js:293:20)
    at Object.Modbus.rtn.read (C:\Users\KJH\Desktop\통신\node_modules\modbus\script.js:49:20)
    at test (C:\Users\KJH\Desktop\통신\modbus_test.js:9:43)
    at Object.<anonymous> (C:\Users\KJH\Desktop\통신\modbus_test.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at errorOrDestroy (internal/streams/destroy.js:168:7)
    at onwriteError (internal/streams/writable.js:391:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_SOCKET_CLOSED'
}
```

**Comment by tbarnhill** [comment]
Can you post your code? I have not done much testing across node versions. I currently have v12.8.1 installed. 

I'll upgrade and see if it breaks. 


### Side thought:
I should probably consider writing some kind of testing procedure for this repository. It would be a chore, but Modbus is an industrial protocol, so long term reliability is a must. modbus.org provides some guidance on testing.

**Comment by dev-guccin** [comment]
An error occurred while executing this code. And I conducted the test using ModbusSlave program.

```
const modbus = require('modbus')
const device = modbus("192.168.219.103",502,1)
//Read
//let myCoil = device.read('c0')
//let myHoldingRegister = await device.read('hr0') 
async function test(){
    let myHoldingRegisters = await device.read('hr1-4') 
    return
}
test()
```

**Comment by nomisx** [comment]
replace function Tcp() with this code:

    function Tcp(ipAddress,port){
        let rtn = {}
    
        let net = require('net')
        let client = new net.Socket()
        rtn.ipAddress = ipAddress
        rtn.port = port
        rtn.online = false
        rtn.send=(data)=>{
            if(rtn.online){
                client.write(data)
            }
            else{
                connect(()=>{client.write(data)})
            }
        }
        rtn.onData = ()=>{}
    
        client.on('data',(res)=>{
           rtn.onData(res)
        })
        
        client.on('close',()=>{
            rtn.online=false
        })
    
        client.on('connect',()=>{
            rtn.online=true
        })
        
        client.on('error',(e)=>{
            rtn.online=false
            console.log(e.message);
        })
    
        let connect=(callback)=>{
            client.connect(rtn.port, rtn.ipAddress, ()=> {
                if(callback){callback()}
            })
    
        }
    
        return rtn
    }

Changes are: 
if(client.writable){     ->    if(rtn.online){ 

and adding:
client.on('error',(e)=>{
        rtn.online=false
        console.log(e.message);
    })

**Comment by boatbodger** [comment]
I can confirm that nomisx's suggestions resolve this problem for me.

**Comment by Kuchengnom** [comment]
I can also confirm that, this worked for me. Same Issue as described above. (node v16.13.x)

**Comment by kv0the91** [comment]
I had the same issue. The Answer from "nomisx" fixed it.
On my Raspberry PI I have NodeJs v18.13.0 installed.
Just replace the function Tcp() from the file "<Your_NodeJs_Project_Folder>/node_modules/modbus/script.js" with the new one "nomisx" has sent.
Thanks a lot!

**Comment by kripton** [comment]
Ping @tbarnhill , I'm experiencing the same.

**Comment by ryangriggs** [comment]
@tbarnhill follow-up to determine if this patch will be incorporated into the repo.

**Comment by tbarnhill** [comment]
Patch has been incorporated
